
services:
  ros2_ndi_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_ndi_tracker
    volumes:
      # 挂载 ROM 文件目录
      - ./rom_files:/opt/ndi/rom_files
      # 挂载源代码目录
      - ./src:/ros2_ws/src/ros2_ndi_tracker
      #挂载日志目录
      - ./logs:/ros2_ws/logs
      # 挂载设备目录
      - /dev:/dev
    devices:
      # 允许访问所有设备
      - /dev/ttyUSB0:/dev/ttyUSB0  # 替换为实际设备路径
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=1
    network_mode: host
    privileged: true
    # Start with a command that keeps the container running
    command: bash -c "source /ros2_ws/install/setup.bash && ros2 run ros2_ndi_tracker ndi_tracker_node || bash"